Step1 [부산대 Android_김주송] 2주차 과제 제출합니다. (STEP1)
kakao-tech-campus-2nd-step2/android-map-keyword pull request #13
Opened 2024-07-02 12:10 UTC by jooiss

## 코드 작성 시, 어려웠던 점
- 데이터베이스를 안드로이드 스튜디오에서 다루는 것이 처음이라 학습하는 데 시간이 많이 소요됐습니다.

## 중점적으로 리뷰해주셨으면 하는 부분
- 데이터에 접근하는 클래스를 분리해보았는데, 제가 한 방식에서 논리적 오류가 있는 부분이 있는지 궁금합니다.
- 어떠한 방식으로 데이터 관리 클래스를 나누는 것이 효율적인지에 대해 궁급합니다. 
(데이터 클래스와 Contract 분리하여 관리 또는 Contract에서 데이터 클래스 관리)

---

정성스러운 리뷰 너무 도움됩니다 멘토님. 더 열심히 학습하도록 하겠습니다. 정말 감사합니다!

2024-07-04 18:22 UTC, LeeOhHyung requested changes
@jooiss 2주차 step1 과제도 고생많으셨습니다.
코멘트 확인 한번 부탁드립니다

2024-07-04 18:22 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        }
p2; MainActivity onCreate 에서 데이터를 삽입하기 때문에, 앱이 실행될때마다 중복해서 값이 들어갈것으로 보입니다. 
제출하신 step1 단계에서는 id를 활용하지 않으므로 각 row의 데이터가 서로 다르다는것을 구분해줄 방법이 없을것 같네요.

즉, 1회에 한해서 한번만 데이터가 삽입되도록 처리가 필요할것 같습니다

2024-07-04 18:22 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/map/PlaceContract.kt
> +}
## 질문
1. `-Contract` 라는 이름을 사용한 이유가 있을까요. 특정한 제약조건을 설정하고 싶으셨던 상황인가요?
2. `PlaceContract.Place` 를 사용하는 곳을 보면, 상수값 사용 목적인것 같습니다. `BaseColumns` 를 상속받도록 하신 이유가 궁금합니다.

2024-07-05 01:35 UTC, jooiss commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        }
STEP2에 함께 처리하도록 하겠습니다. 감사합니다!

2024-07-05 04:56 UTC, jooiss commented on app/src/main/java/campus/tech/kakao/map/PlaceContract.kt
> +}
1. [Android SQLite](https://developer.android.com/training/data-storage/sqlite?hl=ko#kotlin)
SQLite에 익숙치 않아 안드로이드 공식 문서를 참고하였습니다.

2. BaseColumns를 사용하면 _ID라고 하는 기본 키 필드를 상속하여 데이터베이스가 Android 프레임워크와 조화롭게 작동하는데 도움이 될 수 있다고 하여 사용하였습니다.

2024-07-08 05:02 UTC, LeeOhHyung approved these changes
LGTM~ Step2 과제도 화이팅입니다

2024-07-08 05:02 UTC, merged