강원대 Android_윤채원 2주차 과제 Step1
kakao-tech-campus-2nd-step2/android-map-keyword pull request #15
Opened 2024-07-02 16:15 UTC by settle54

# 코드작성 시, 어려웠던 점

- `SQL`이 처음이라서 어떻게 써야하는 건지 많이 공부해야 했다... (` ;` 을 안 적어서 한참을 고생했다)
- `MVVM 패턴`이 뭔지 정확하게 잘 모르겠다.   
Model -> ViewModel -> View...   
우선 View는 ViewModel에서, ViewModel은 Model에서 데이터가 접근가능하도록 구현하려 노력했다.
-`ViewModel`을 지난 주차에 써볼까 하다가 실패했는데 이번 주차에 만나니까 너무 어렵다....

***

# 중점적으로 봐주셨으면 하는 부분

- MVVM 패턴을 잘 지켰는지 확인해주셨으면 합니다.
- 가령, `insertPlace`를 하면 View -> ViewModel -> DB 이렇게 세 번 연속으로 메소드가 중첩되는데, 이게 맞는건지 잘 모르겠습니다....
- 검색어를 저장하는 것은 `SharedPreferences`를 사용해도 괜찮은지 알고 싶습니다.

2024-07-04 17:40 UTC, kold-brewed requested changes

2024-07-04 17:40 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/PlacesDBHelper.kt
> +    companion object {
코틀린으로 클래스를 정의할 때 companion object는 거의 클래스 최하단에 위치시키는 것을 권장하고 있어요~ 
아래 코틀린 공식문서에 있는 코딩 컨벤션 페이지 남겨둘게요! 여유있을 때 한번 슥 읽어보시면 좋을 것 같아요.

🔗 코틀린 코딩컨벤션 > [클래스 레이아웃](https://kotlinlang.org/docs/coding-conventions.html#class-layout)

2024-07-04 17:40 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/PlacesDBHelper.kt
> +        db.close()
this.writableDatabase에 접근할 때 SQLiteException으로 인해 앱이 종료될 수 있어서 적절히 예외처리가 필요합니다. 더 위에 라인에 정의된 readableDatabase, execSQL도 마찬가지구요.

하려던 동작이 실패했을 때 별다른 처리 없이 넘어가도 된다면 여기서 try-catch로 감싸는 방법도 있겠고,
유저에게 오류 문구를 띄워주고 싶다면 더 상위로 올라가 insertPlace()를 호출하는 곳에서 try로 감싸고 catch에서 토스트를 띄우는 방법도 있어요.

예외를 던지는지 확인하는 방법은 해당 함수/변수 위에서 우클릭 > Go To > Declaration or Usages를 클릭하시면 함수 정의를 보실 수 있고, 그 위 주석에 Throws가 있는지 확인해보시면 됩니다.
`
Throws: SQLException – if the SQL string is invalid
`

물론 기본적으로 기능을 완성하는 것이 우선이겠고, 시간내에 완성되었다면 이렇게 놓친 예외처리가 없는지도 한번 점검해주시면 앱의 완성도를 높일 수 있습니다!

2024-07-04 17:40 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/PlacesDBHelper.kt
> +    @SuppressLint("Range")
여기 @SuppressLint 어노테이션을 추가하신 이유가 궁금합니다~

2024-07-04 17:40 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/MapRepository.kt
> +    private var localDB: PlacesDBHelper
localDB는 한번 초기화되고나면 다시 할당할 일이 없으니 val로 변경해주세요~
아마..init 블럭 안에서 초기화를 하는 것 때문에 var로 정의하신게 아닐까 추측이 되어 말씀드려보자면, init블럭 안에서는 val로 정의해도 초기화가 가능합니다. 사실 이것보다는 그냥 한줄로 이렇게 정의하는 걸 더 깔끔해요. 보기싫은 경고 밑줄도 안뜰테구요.
`private val localDB: PlacesDBHelper = PlacesDBHelper(context)`

이외 다른 곳들은 data class 정의하실 때에도 그렇고 잘 지켜주셨네요 👍

2024-07-04 17:40 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/MapRepository.kt
> +            insertInitialData()
if문을 여러줄에 걸쳐서 작성하실 때에는 중괄호를 붙여주시는 것이 좋습니다.
```suggestion
        if (!dbFile.exists()) {
            insertInitialData()
        }
```
🔗 코틀린 스타일 가이드 > [중괄호](https://developer.android.com/kotlin/style-guide?hl=ko#braces)

2024-07-04 17:40 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/MapRepository.kt
> +            val drugStore = Place("약국" + i, "서울 강남구 대치동 " + i, "약국")
문자열을 동적으로 구성할 땐 아래와 같이 String Template을 이용해 좀 더 코틀린스럽게 작성하시는 것을 추천드려요.
```suggestion
            val drugStore = Place("약국$i", "서울 강남구 대치동 $i", "약국")
```
🔗 코틀린 > [String templates](https://kotlinlang.org/docs/strings.html#string-templates)

2024-07-04 17:40 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/Place.kt
> +    constructor(): this("", "", "")
요 생성자는 어떤 경우에 사용하려고 만드신 건지 궁금하네요!

2024-07-04 17:40 UTC, kold-brewed commented on app/src/main/res/layout/activity_main.xml
> +        android:text="검색 결과가 없습니다."
앞으로 문구는 레이아웃 xml에 바로 넣기보다는 strings.xml 파일에 정의하고 참조하는 식으로 작성해주세요~

2024-07-04 17:40 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/MapRepository.kt
> +            localDB.insertPlace(drugStore)
localDB.insertPlace()가 한번 호출될 때마다 데이터베이스 연결이 열리고(writableDatase) 닫히고(db.close) 있어요.
데이터베이스 연결을 열고 닫는건 리소스가 많이 드는 작업인데, Place 정보 60개를 넣는데 매번 데이터베이스 연결도 60번 열리고 닫히고 있는거죠. 뭔가 아주 비효율적인 냄새가 납니다..!

DB에 넣을 list를 먼저 구성하고, localDB.insertPlace()에 배열을 넘겨서 단 한번의 연결로 60개의 데이터가 삽입되도록 해주시면 데이터가 훨씬 늘어났을 때에도 앱 속도를 지킬 수 있을 것 같아요.

조금 더 도움이 될만한 링크도 남겨두겠습니다.
🔗 안드로이드 디벨로퍼스 > [데이터베이스 연결 유지](https://developer.android.com/training/data-storage/sqlite?hl=ko#PersistingDbConnection)

2024-07-04 17:40 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +
MVVM 패턴에 대한 리뷰는 기능이 모두 완성되고 Activity에 뷰를 다루는 코드가 채워진 시점에 피드백 남기겠습니다.

2024-07-04 17:40 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/PlacesViewModel.kt
> +    }
지금 과제에서 굳이 필요없는데 넣어서 복잡해지는 것 같다...는 충분히 그렇게 생각하실 수 있는 단계라고 생각해요.

실제로 큰 회사에서 개발자로 일을 하게되면 하나의 기능을 만들고 그대로 끝나는게 아니라, 그 기능을 긴 시간에 걸쳐 확장하고 유지보수하게 됩니다. 그 과정에서 처음엔 3,4개 파일 정도였던 코드규모가 수십, 수백개로 늘어납니다. 당연히 개발 난이도도 올라가구요. 디자인 패턴은 이런 상황을 잘 헤쳐나가기 위한 방법론이예요. 극단적으로 생각해서 지금처럼 UI가 단순한 화면 1개짜리 앱을 1회성으로 만든다면 MVVM과 같은 패턴은 오히려 불필요하게 코드만 복잡해지는 오버스펙일 수도 있다고 생각합니다.

지금은 ViewModel에서 그냥 바로 DBHelper 불러다 쓰면 안되나..하는 생각이 드실 수 있지만, 앞으로 2단계, 3단계 그리고 네트워크 통신까지 구현하면서 ViewModel과 Repository의 모습이 지금보다는 복잡해질거예요. 그런 상황을 미리 대비하기 위해 레이어를 나누는 연습을 한다고 생각해주시면 좋을 것 같네요~

2024-07-04 17:40 UTC, kold-brewed commented on app/src/main/res/layout/activity_main.xml
> +            android:hint="검색어를 입력해 주세요."
> 검색어 저장에 SharedPreferences를 사용해도 괜찮을지?

저장한 검색어로 어떤걸 할건지에 따라 다를 것 같아요.
그냥 정말 단순히 검색어 String 목록만 있으면 된다의 정도라면 써도 무방하겠습니다.

그런데 이제 검색어를 사용순으로 정렬해준다거나, 오래된 검색어는 지운다거나 하는 좀 더 복잡한 요구사항들이 있다면 검색어 관련 추가적인 정보들을 같이 저장하기엔 SharedPreferences는 구조적으로 데이터를 담을 수 없어 적절하지 않아요.

2024-07-05 05:59 UTC, settle54 commented on app/src/main/java/campus/tech/kakao/map/Place.kt
> +    constructor(): this("", "", "")
insertPlace()를 할 때 만약 공백인 값이 들어갈 경우를 대비하여서 추가하였습니다!

2024-07-05 06:08 UTC, settle54 commented on app/src/main/java/campus/tech/kakao/map/PlacesDBHelper.kt
> +    @SuppressLint("Range")
```kotlin
cursor.getString(cursor.getColumnIndex(NAME))
``` 
을 할 때, 가져오는 열의 유효성을 IDE가 모르는지
**Value must be ≥ 0 but getColumnIndex can be -1**
경고가 떠서 IDE가 하라는대로 어노테이션을 추가했습니다.
데이터를 가져오고자 하는 테이블의 구조가 명확한데도 따로 예외처리를 해주는 것이 좋을까요...?

2024-07-05 15:39 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/Place.kt
> +    constructor(): this("", "", "")
음 혹시 이름과 주소는 있는데 카테고리가 지정되지 않은 경우를 생각하신 것이라면 
프로퍼티를 정의하실 때 기본값을 지정하는 방법도 생각해보시면 좀 더 코틀린스러운 코드로 만드실 수 있을 것 같아요.

🔗 코틀린 > [생성자](https://kotlinlang.org/docs/classes.html#constructors)

2024-07-05 16:02 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/PlacesDBHelper.kt
> +    @SuppressLint("Range")
안드로이드 스튜디오가 띄우는 경고는 생각보다 실수하기 쉬운 부분들을 잘 잡아줄 때가 많습니다. (해결방법에 대한 제안은 좀 불친절한 편입니다😅)

지금까지의 구현으로 살펴보았을 때에 우리는 이름 칼럼이 이 시점에 반드시 존재할 것이기 때문에 getColumnIndex()가 -1을 반환할 일이 없을 거라고 생각해볼 수 있어요. 하지만 담당자가 바뀌고, 데이터 스키마도 바뀌고, 끊임없는 수정이 이뤄지는 과정에서는 항상 실수가 발생합니다. 그때도 지금처럼 칼럼이 존재하는 상황을 100% 확신할 수 있을지, -1을 반환하는 상황이 절대절대 없을 거라고 장담할 수 있는지에 대한 고민은 필요합니다. 만에하나 -1이 넘어갔을 경우에는 @SuppressLint로 처리했기 때문에 앱이 죽을거예요.

여러 가지 처리방식이 있을 수 있을 것 같아요.
1. 지금처럼 @SuppressLint로 경고를 무시.
2. getColumnIndex가 -1이 아닐때만 cursor.getString()으로 넘기도록 분기
3. getColumnIndexOrThrow를 이용해 예외가 던져질 수 있음을 명시하고, try-catch.

그렇지만 1번은 모든 방법을 다 찾아본 뒤에 최후의 수단으로 적용하시는 것을 권해드리고 싶습니다.

2024-07-05 16:07 UTC, merged