전남대 Android_이민서_2주차 과제_Step 1
kakao-tech-campus-2nd-step2/android-map-keyword pull request #16
Opened 2024-07-02 17:25 UTC by LEEMINSEO00

# 2주차 과제_Step 1
## 검색어 저장: 1단계 로컬 데이터
### 코드 작성하면서 어려웠던점
- SQL을 안드로이드 스튜디오 내부에서 다루는 것은 처음이라 감이 잘 잡히지 않습니다. 강의 자료와 강사님이 슬랙에 올려주신 예시 코드를 참고하여 최대한 따라해보았습니다.
- MVVM 아키텍쳐 패턴에 대해 구글링을 통해 개념을 알아보았지만 사용해본적이 없어 코드에 적용시키려니 잘 모르겠습니다. 장점, 단점도 알아보았지만 잘 와닿지 않습니다.(왜 쓰는지가 궁금합니다.)

### 멘토님이 중점적으로 리뷰해주셨으면 하는 부분
- MVVM 아키텍쳐 패턴(또는 다른 아키텍쳐 패턴)을 적용하는 방법을 알고 싶습니다. 아키텍쳐 패턴의 구조를 알아도 View, ModelView, Model에 각각 코드를 어떻게 작성해야하는지 알고 싶습니다. (제가 작성한 코드는 당연히 MVVM 아키텍쳐 패턴 적용이 안 된거겠죠..?)
- SQLite가 아직 미숙합니다. 구현 안된 부분이 있는지, 불필요한 코드가 있는지, 제대로 작성한 것인지 등을 점검 부탁드립니다.
- 요구 사항에 맞게 로컬 데이터베이스가 생성된게 맞을까요?(실행 결과 이미지 첨부합니다.)
- Run 할 때 마다 같은 데이터가 또 저장됩니다. 이를 방지하는 코드가 분명 필요하겠죠?

## 구현 기능 목록에 작성하지 않았지만 세부적으로 추가한 것
- 장소 이름, 주소, 카테고리 모두 입력 시 검색이 되도록 코드를 작성했습니다.(아직 1단계라 실행 화면에서 확인은 못했습니다.)
- 1주차 과제에서 피드백 주신대로 문자열 리소스를 string.xml을 사용하여 표시했습니다.

## 구현 결과
<img width="239" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/android-map-keyword/assets/104787304/13a5cf09-6a43-460b-856b-25210da3b71c">
<img width="1432" alt="image" src="https://github.com/kakao-tech-campus-2nd-step2/android-map-keyword/assets/104787304/741197bc-3df3-4a2f-9187-03d5b0a7fd51">
(일단 데이터베이스가 생성되어 과제를 제출합니다)

2024-07-03 14:05 UTC, omjoonkim requested changes
> MVVM 아키텍쳐 패턴에 대해 구글링을 통해 개념을 알아보았지만 사용해본적이 없어 코드에 적용시키려니 잘 모르겠습니다. 장점, 단점도 알아보았지만 잘 와닿지 않습니다.(왜 쓰는지가 궁금합니다.)
> MVVM 아키텍쳐 패턴(또는 다른 아키텍쳐 패턴)을 적용하는 방법을 알고 싶습니다. 아키텍쳐 패턴의 구조를 알아도 View, ModelView, Model에 각각 코드를 어떻게 작성해야하는지 알고 싶습니다. (제가 작성한 코드는 당연히 MVVM 아키텍쳐 패턴 적용이 안 된거겠죠..?)
아래의 코멘트 남겼습니다. 공식 문서의 내용을 읽고 적용해본 이후, 느끼신 장단점을 정리하여 코멘트로 남겨주세요. 남겨주실 코멘트를 바탕으로 피드백을 드릴 수 있을 것 같습니다.

> SQLite가 아직 미숙합니다. 구현 안된 부분이 있는지, 불필요한 코드가 있는지, 제대로 작성한 것인지 등을 점검 부탁드립니다.

db 사용 부분 코멘트 남겼습니다.  :)


> 요구 사항에 맞게 로컬 데이터베이스가 생성된게 맞을까요?(실행 결과 이미지 첨부합니다.)
Run 할 때 마다 같은 데이터가 또 저장됩니다. 이를 방지하는 코드가 분명 필요하겠죠?

네 DB생성은 알맞게 되었습니다. run할 때마다 같은 데이터가 저장되는 이유는 저장되어있는 데이터를 확인하지 않고 항상 데이터를 저장하기 때문입니다. 이를 방지하기 위해서는 db에 데이터가 없을 때, 기본 데이터를 추가하도록 코드를 작성해주시면 됩니다.

2024-07-03 14:05 UTC, omjoonkim commented on app/src/main/res/layout/activity_main.xml
> +    <ListView
ListView 대신 [RecyclerView](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView) 사용을 권장합니다. 
ListView를 사용할 때 직접 구현해줘야 하는 여러 기능들(재활용, 뷰홀더 패턴등)을 RecyclerView는 사용하기 편한 형태로 제공해줍니다.

2024-07-03 14:05 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        inputSearch = findViewById(R.id.inputSearch)
지난 1주차 과제 때 제안드린 것처럼 ViewBinding 사용을 통해 선언문을 제거해보는 것이 어떨까요?

2024-07-03 14:05 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/DbHelper.kt
> +        onCreate(db)
onCreate는 라이프사이클 컬백에 가깝기 때문에 직접 호출하는 것은 의미상 지양하는 것이 좋습니다. 
Table을 생성하는 함수를 분리하여 호출하는 것이 좋을 것 같아요 :)

2024-07-03 14:05 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/DbHelper.kt
> +        val db = writableDatabase
db를 사용한 이후에 언제 close해주는 것이 좋을까요?

컴포넌트의 lifeCycle에 맞추어서
사용한 직후.
어느 것이 더 좋을지 생각해본 뒤, PR에 반영해주세요~!

2024-07-03 14:05 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +    private fun insertInitialData(dbHelper: DbHelper) {
과제에 요구사항이 MVVM패턴을 사용하는 것이기 때문에 Activity내의 모든 코드가 존재해서는 안됩니다.
[안드로이드 공식 문서의 가이드](https://developer.android.com/topic/architecture)를 공부하고 적용해주세요.

2024-07-03 14:05 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +    private fun searchDatabase(query: String) {
searchDatabase는 호출되는 곳이 없는 것 같은데 맞을까요??

2024-07-03 14:18 UTC, LEEMINSEO00 commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +    private fun searchDatabase(query: String) {
넵 맞습니다

2024-07-03 14:50 UTC, LEEMINSEO00 commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        inputSearch = findViewById(R.id.inputSearch)
제가 그 부분을 놓쳤었네요. 사용하니 훨씬 깔끔하고 편합니다! 감사합니다

2024-07-04 02:16 UTC, LEEMINSEO00 commented on app/src/main/java/campus/tech/kakao/map/DbHelper.kt
> +        val db = writableDatabase
구현했습니다. 피드백을 잘 이해하고 반영한 것인지 확인 부탁드립니다!

2024-07-04 02:16 UTC, LEEMINSEO00 commented on app/src/main/java/campus/tech/kakao/map/DbHelper.kt
> +        onCreate(db)
creatTable 함수를 만들어 따로 분리했습니다

2024-07-04 02:16 UTC, LEEMINSEO00 commented on app/src/main/res/layout/activity_main.xml
> +    <ListView
RecyclerView로 수정했습니다

2024-07-04 02:21 UTC, LEEMINSEO00 commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +    private fun insertInitialData(dbHelper: DbHelper) {
MainViewModel.kt를 생성하고 코드를 수정하여 패턴을 적용시켜 보았습니다.
코드가 분리되다 보니 가독성이 더 좋은 것 같고 코드 재사용에 좋을 것 같습니다. 자료를 찾아보며 작성했지만 아직 미숙한 탓인지 어렵습니다.

2024-07-05 13:42 UTC, omjoonkim approved these changes
2단계 리뷰의 편의를 위해 이 PR은 머지하도록 하겠습니다. 새로 추가된 코멘트는 다음 PR에서 꼭 적용해주세요~!

2024-07-05 13:42 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        /* ViewBinding을 사용하기 때문에 주석 처리
PR을 요청할때에는 리뷰어를 위해 불필요한 코드는 제거하는 것이 좋습니다. 이렇게 사용하지 않는 주석코드는 다음부터는 제거 부탁드려요~!

2024-07-05 13:42 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/DbHelper.kt
> +        writableDatabase.use { db ->
use 사용 좋습니다. 👍

2024-07-05 13:42 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +            _searchResults.postValue(results)
postValue와 setValue의 차이가 무엇일까요? 여기서는 어떤 함수를 사용하는 것이 좋을지 한번 찾아보고 의견을 코멘트로 남겨주세요. :)

2024-07-05 13:42 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +                        dbHelper.insertData("카페 $i", "서울 성동구 성수동 $i", "카페")
데이터를 조작하는 행위를 우리는 흔히 비즈니스로직이라고 얘기합니다. 뷰모델에 이러한 비즈니스 로직이 많아지게 되면 뷰모델의 코드양이 많아지고 코드 복잡성이 증가하게 됩니다. 이전에 공유드렸던 [공식 문서](https://developer.android.com/topic/architecture)에서 Repository가 어떤역할을 하는지 알아보고 코드에 적용해봐주세요.

2024-07-05 13:42 UTC, merged

2024-07-07 05:22 UTC, LEEMINSEO00 commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +            _searchResults.postValue(results)
setValue는 메인 쓰레드에서 LiveData의 값을 변경하며 호출 시 즉시 값이 변경됩니다. postValue는 백그라운드에서 LiveData의 값을 변경하며 비동기적으로 값을 업데이트하므로 호출 시 즉시 값이 변경되지 않습니다.
여기서는 백그라운드에서 데이터베이스 쿼리 결과를 업데이트 하므로 postValue가 적절하다고 생각합니다.

2024-07-07 06:31 UTC, LEEMINSEO00 commented on app/src/main/java/campus/tech/kakao/map/MainViewModel.kt
> +                        dbHelper.insertData("카페 $i", "서울 성동구 성수동 $i", "카페")
다시 공식 문서를 정독하고 적용시켜 봤습니다. 제대로 구현했는지 확인 부탁드립니다! 다시 읽으니 전 보다 더 아키텍쳐가 이해되는 것 같습니다.