2주차 1단계
kakao-tech-campus-2nd-step2/android-map-keyword pull request #24
Opened 2024-07-03 06:57 UTC by seyoung34

1단계와 2단계 구분이 모호해진 감이 조금 있습니다...
데이터베이스를 MainActivity가 onCreate할 때마다 생성하는게 좀 마음에 들지 않아서 
디버깅/테스트 용 버튼으로 조작하고 있습니다.
리스트뷰는 리사이클러뷰로 교체할 예정입니다!

2024-07-05 12:53 UTC, kold-brewed requested changes

2024-07-05 12:53 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/DatabaseHelper.kt
> +    }
코틀린 컨벤션 중에는 클래스 내에 여러 요소들의 순서와 관련된 내용도 있어요. 그 중에서 companion object는 거의 클래스 최하단에 위치시키는 것을 권장하고 있습니다. 아래 코틀린 공식문서에 있는 코딩 컨벤션 페이지 남겨둘게요! 여유있을 때 한번 슥 읽어보시면 좋을 것 같아요.

🔗 코틀린 코딩컨벤션 > [클래스 레이아웃](https://kotlinlang.org/docs/coding-conventions.html#class-layout)

2024-07-05 12:53 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/DatabaseManager.kt
> +                    getString(getColumnIndexOrThrow("kind"))
칼럼명은 변하지 않는 값이기도 하고, put/get 할 때 두 군데에서 쓰이고 있으니 상수로 선언해두고 쓰시면 오타로 인한 오류 상황을 줄일 수 있어요! 기존에 DatabaseHelper에 정의하신 걸 이용해도 좋겠네요~

2024-07-05 12:53 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/DatabaseManager.kt
> +    private val db: SQLiteDatabase = dbHelper.writableDatabase //open하고 실제 데이터베이스..?
요 this.writableDatabase에 접근할 때에는 예외 발생(SQLiteException) 가능성이 있어서 적절히 try-catch로 처리해주지 않으면 앱이 그냥 종료되어버리는 경우가 생길거예요. DatabaseHelper로 전달되어 execSQL()함수를 호출할 때에도 발생할 수 있구요.

예외를 던지는지 확인하는 방법은 해당 함수/변수 위에서 우클릭 > Go To > Declaration or Usages를 클릭하시면 함수 정의를 보실 수 있고, 그 위 주석에 Throws가 있는지 확인해보시면 됩니다.
Throws: SQLException – if the SQL string is invalid

단계별 기능을 완성하신 뒤에 시간이 남는다면 이렇게 놓친 예외처리가 없는지도 한번 점검해주시면 앱의 완성도를 높일 수 있습니다!

2024-07-05 12:53 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/DatabaseManager.kt
> +        with(cursor) {  //객체의 범위, 객체 이름을 지정하지 않아도됨!
코틀린 Scope function을 잘 사용해주셨네요 👍
적절히 잘 활용하면 이렇게 코드를 간결하게 만들 수 있어요.
하지만 어떤 상황에서는 with의 중괄호로 인해 들여쓰기가 너무 깊어지는 상황도 생길 수 있을거예요. 앞으로도 사용하실 때에 편리함과 가독성을 잘 고려주시면 좋겠습니다~

2024-07-05 12:53 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +                Toast.makeText(this, "검색어를 입력하세요", Toast.LENGTH_SHORT).show()
잠깐 사용하고 지울 테스트 용도의 문구는 하드코딩해도 괜찮지만, 정식 기능으로 사용될 문구는 앞으로 strings.xml에 정의하고, R.string으로 접근하도록 작성해주시면 좋겠습니다!

2024-07-05 12:53 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/Place.kt
> +import androidx.annotation.DrawableRes
클래스 내에 DrawableRes를 사용하셨다가 코드가 지워지면서 import문이 남았네요!
요런 불필요한 import문은 안드로이드 스튜디오 상단에 Code - Optimize Imports로 쉽게 정리하실 수 있어요.
파일 커밋하기 전에 한번씩 해주시면 코드를 깔끔하게 유지하실 수 있습니다.

2024-07-05 12:53 UTC, kold-brewed commented on app/src/main/res/layout/activity_main.xml
> +        android:hint="검색어를 입력해 주세요"
레이아웃 xml에 정의하시는 문자열도 string.xml에 정의해주시면 좋겠습니다!

2024-07-05 12:53 UTC, kold-brewed commented on app/src/main/res/layout/activity_main.xml
> +        android:background="#CDDC39"/>
activity_main.xml에 정의된 UI 요소들의 속성 정의 순서가 다소 뒤섞여있어요. 
안드로이드 스튜디오 상단바 Code - Reformat code로 컨벤션을 정리할 수 있습니다. 역시 파일 커밋하기 전에 한번씩 해주시면 코드 가독성을 높일 수 있습니다~

2024-07-05 12:53 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/DatabaseHelper.kt
> +class DatabaseHelper(context : Context) : SQLiteOpenHelper(context, DATABASE_NAME, null, 1) {
데이터베이스에 데이터를 관리하는 코드를 2개의 클래스로 나누어 작성해주셨네요.
테이블을 만들고, 업그레이드하는 것과 데이터를 insert, delete하는 작업은 모두 연관되어 있기 때문에 지금처럼 기능이 크지 않을 때에는 한 개의 클래스가 데이터베이스와 관련된 책임을 다하도록 구현하는 쪽을 좀 더 권해드리고 싶어요~

2024-07-05 12:53 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/DatabaseHelper.kt
> +class DatabaseHelper(context : Context) : SQLiteOpenHelper(context, DATABASE_NAME, null, 1) {
데이터베이스에 데이터를 관리하는 코드를 2개의 클래스로 나누어 작성해주셨네요.
테이블을 만들고, 업그레이드하는 것과 데이터를 insert, delete하는 작업은 모두 연관되어 있기 때문에 지금처럼 기능이 크지 않을 때에는 한 개의 클래스가 데이터베이스와 관련된 책임을 다하도록 구현하는 쪽을 좀 더 권해드리고 싶어요~

2024-07-05 12:53 UTC, kold-brewed commented on README.md
> +3. 리스트뷰 어댑터 설계
1단계 요구사항을 잘 작성해주셨네요!
2단계를 구현하실 때에 MainActivity에 테스트용 코드는 제거해주시고, 
MVVM 패턴에 맞게 레이어를 분리해서 View에 해당하는 로직만 포함될 수 있게, 그리고 ViewModel에서 View에 그릴 데이터를 다듬는 로직이 담길 수 있게 작성해주시면 좋겠습니다 😃

2024-07-05 16:09 UTC, merged

2024-07-06 07:02 UTC, seyoung34 commented on app/src/main/res/layout/activity_main.xml
> +        android:hint="검색어를 입력해 주세요"
hint에 들어가는 "검색어를 입력해 주세요"를 string.xml에 정의하는게 좋다는 말씀이실까요?

2024-07-07 13:03 UTC, kold-brewed commented on app/src/main/res/layout/activity_main.xml
> +        android:hint="검색어를 입력해 주세요"
네네 맞습니다. 안드로이드에서는 문자열을 strings.xml에 정의하도록 가이드하고 있어요.
🔗 https://developer.android.com/guide/topics/resources/string-resource#String

이렇게 하드코딩하는 경우에 안드로이드 스튜디오 상에서도 노란줄로 lint warning으로 표시해주는 걸 보셨을거예요.
별도 xml에 문자열을 정의하는 건 동일한 문자열을 여러 곳에서 사용할 경우에도 유용하고, 다국어를 지원하기 위해서 이용하기도 합니다.