충남대 Android_김선규 2주차 과제 Step2
kakao-tech-campus-2nd-step2/android-map-keyword pull request #35
Opened 2024-07-04 23:54 UTC by kimseongyu

## Step 2

**코드 작성하면서 어려웠던 점**

- DBHelper에서 1개의 database 생성에서 2개의 database를 생성으로 변경하려고 하니 오류가 발생했습니다. 
일단, version을 상승시키니 문제가 해결되었는데 그 이유가 궁금합니다.
- MVVM을 지키며 코드를 작성하려고 하는 중 View Model에서 state flow를 사용하게 되었는데 이를 이해하고 적용하는데 시간이 걸렸습니다.
- UI쓰레드와 분리하기 위해 lifecycleScope를 사용하였는데 아직 완전히 이해하지 못하여 좀 더 공부해야 될 거 같습니다.

**코드 리뷰 시, 멘토님이 중점적으로 리뷰해줬으면 하는 부분**

- database, activity, layout에서 변수명이나 함수명을 지을 때 어떤 경우에 snake case를 써야 하는지 camel case를 써야 하는지 잘 모르겠습니다. 맞게 변수명을 작성했는지 봐주시면 감사하겠습니다.
- viewBinding을 처음 사용해봤는데 맞게 사용하고 있는지 궁금합니다.
- RecyclerView에서 setClickListener를 설정해주기 위해 adapter의 인자로 함수를 주었는데 맞게 구현한 방법인지 궁금합니다. 
또한, 이 방법이 MVVM을 따라 구현한 것인지도 의문입니다.

2024-07-05 14:28 UTC, omjoonkim requested changes
1단계 PR의 코멘트도 반영 부탁드립니다. :)

> DBHelper에서 1개의 database 생성에서 2개의 database를 생성으로 변경하려고 하니 오류가 발생했습니다.
일단, version을 상승시키니 문제가 해결되었는데 그 이유가 궁금합니다.

기존 앱에 이미 DB가 생성되어있기 때문입니다. DB의 구조를 변경하기 위해서는 버전을 올리거나 혹은 앱을 삭제한 뒤 재설치 하시면 됩니다.

> database, activity, layout에서 변수명이나 함수명을 지을 때 어떤 경우에 snake case를 써야 하는지 camel case를 써야 하는지 잘 모르겠습니다. 맞게 변수명을 작성했는지 봐주시면 감사하겠습니다.

database만 snake case로 변경하시면 될 것 같습니다. ㅎㅎ

> viewBinding을 처음 사용해봤는데 맞게 사용하고 있는지 궁금합니다.

잘 사용하고 계십니다. 👍

> RecyclerView에서 setClickListener를 설정해주기 위해 adapter의 인자로 함수를 주었는데 맞게 구현한 방법인지 궁금합니다.
또한, 이 방법이 MVVM을 따라 구현한 것인지도 의문입니다.

뷰홀더의 UI이벤트를 탐지하기 위한 방법은 여러가지가 존재합니다. 람다를 넘기거나, 인터페이스를 선언하여 이를 활용하거나, 어떨 때는 이벤트 버스 형태를 사용하기도 합니다. 
각각의 방법이 필요할 때가 있으며 상황에 따라 적절하게 사용하면 됩니다. 
현재 작성하신 코드에는 아무런 이상이 없습니다. 좋습니다.

2024-07-05 14:28 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/StoreInfo.kt
> +    const val TABLE_NAME = "storeInfo"
디비 관련 네이밍은 보통 스네이크 케이스를 사용하는 것 같습니다.:)

2024-07-05 14:28 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +    private fun delSearchWord() {
함수명만 봤을때는 검색 단어를 제거하는 것처럼 보이는데, 실제 코드는 리스너를 추가하는 것이기 때문에 함수명과 매칭이 되지 않습니다. 코드의 의미에 맞게 네이밍을 다시 해보세요.

2024-07-05 14:28 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +    private fun detectSearchWindowChanged() {
위 코멘트와 같습니다.

2024-07-05 14:28 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +            viewModel.searchResults.collect {
Activity는 Lifecycle에 따라 생성과 파괴를 반복하므로, Flow를 수집할 때도 Lifecycle을 고려해야 합니다. 그렇지 않으면 메모리 누수나 예기치 않은 동작이 발생할 수 있어요. [아티클](https://developer.android.com/reference/androidx/lifecycle/RepeatOnLifecycleKt)을 참고해 코드를 작성해보세요.

2024-07-05 14:28 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/SavedSearchWordsAdapter.kt
> +        holder.savedSearchWord.text = savedSearchWords[position].searchword
Adapter에서 여러 뷰홀더를 사용할 경우 onBindViewHolder는 어떻게 변경되어야 할까요? 여러 뷰홀더를 사용할때를 대비하여 코드를 수정해보세요.

2024-07-07 11:34 UTC, kimseongyu commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +            viewModel.searchResults.collect {
다음 사이트를 참고해서 어떻게 작동하는 지 이해하고 수정했습니다.
- [documentation](https://developer.android.com/reference/kotlin/androidx/lifecycle/package-summary#(androidx.lifecycle.Lifecycle).repeatOnLifecycle(androidx.lifecycle.Lifecycle.State,kotlin.coroutines.SuspendFunction1))
- [구현된 sourcecode](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:lifecycle/lifecycle-runtime/src/commonMain/kotlin/androidx/lifecycle/RepeatOnLifecycle.kt?q=file:androidx%2Flifecycle%2FRepeatOnLifecycle.kt%20function:repeatOnLifecycle)
- [참고한 blog](https://kotlinworld.com/228)

2024-07-07 11:37 UTC, kimseongyu commented on app/src/main/java/campus/tech/kakao/map/SavedSearchWordsAdapter.kt
> +        holder.savedSearchWord.text = savedSearchWords[position].searchword
여러 뷰 홀더라는게 `when`으로 경우를 나누어서 해결해야 되는지 `savedSearchWords[position]`를 변수로 따로 선언하여 코드를 간략하게 하라는 뜻인지, 헷갈렸으나 일단 후자로 해결하였습니다.

2024-07-07 14:18 UTC, omjoonkim approved these changes
1. 컨플릭트가 제대로 해결되지 않은 것 같습니다.
2. 컨플릭트를 자체적으로 해결하고 앱을 실행해봤을 때 검색결과가 나타나지 않습니다.

코멘트 내용과 함께 충돌을 해결하고 코드를 개선해주세요. 

PR은 규칙에 따라 머지하도록 하겠습니다~!

2024-07-07 14:18 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/StoreInfoDBHelper.kt
> +=======
충돌이 올바르게 해결되지 않은 것 같습니다. 의도하신 동작이 제대로 되는지 확인해주세요.

2024-07-07 14:18 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/SearchRepository.kt
> +        if(!hasStoreInfo()) return
```suggestion
        if(hasStoreInfo()) return
```
요구사항대로 동작하려면 코드가 위와 같이 변경되어야 할 것 같아요. ㅎㅎ

2024-07-07 14:18 UTC, merged