전남대 Android_이민서_2주차 과제_Step 2
kakao-tech-campus-2nd-step2/android-map-keyword pull request #48
Opened 2024-07-05 07:23 UTC by LEEMINSEO00

# 2주차 과제_Step 2
## 검색어 저장: 2단계 검색
### 코드 작성하면서 어려웠던 점
- MVVM 아키텍쳐 패턴을 적용하는 것이 어려웠습니다.
- LinearLayout만 사용하다가 ConstraintLayout을 사용하니 새로웠지만 아직 조금 낯선 감도 있습니다.

### 멘토님이 중점적으로 리뷰해주셨으면 하는 부분
- Step 1 리뷰에 적어주신대로 자료를 참고하여 MVVM을 적용시켜봤는데 제대로 한 것인지 궁금합니다.
- 레이아웃을 구현하는 코드가 불필요한 것 없이 잘 작성되었는지 궁금합니다.

### 요구 사항에 없었지만 세부적으로 추가한 것
- 장소 이름, 주소, 카테고리로 검색이 되도록 코드 작성
- 최근 검색어가 맨 앞(좌측)에 저장되도록 설정

(Step 1 브랜치가 merge 되지 않아 Step 1의 기능을 담은 Step2 브랜치를 생성해 작업을 수행했습니다.)

2024-07-05 15:06 UTC, omjoonkim requested changes
> Step 1 리뷰에 적어주신대로 자료를 참고하여 MVVM을 적용시켜봤는데 제대로 한 것인지 궁금합니다.

잘 작성하셨습니다. 역할에 맞게 컴포넌트와 코드가 잘 분리되어있다고 보여지네요. 


> 레이아웃을 구현하는 코드가 불필요한 것 없이 잘 작성되었는지 궁금합니다.

코멘트 남겼습니다~!

이전 PR 코멘트도 반영 부탁드려요~!

2024-07-05 15:06 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/SearchAdapter.kt
> +    private val results = mutableListOf<String>()
String대신 데이터 클래스를 만들어 코드를 명시적으로 작성해보는 것이 어떨까요?

2024-07-05 15:06 UTC, omjoonkim commented on app/src/main/res/layout/item_result.xml
> +    <LinearLayout
LinearLayout대신 ConstraintLayout의 속성을 활용하여 뎁스 없이 UI구성이 되도록 코드르 변경해보세요.

2024-07-07 05:55 UTC, LEEMINSEO00 commented on app/src/main/java/campus/tech/kakao/map/SearchAdapter.kt
> +    private val results = mutableListOf<String>()
data class 생성 후 String을 SearchResult로 변경하여 적용시켰습니다.

2024-07-07 06:07 UTC, LEEMINSEO00 commented on app/src/main/res/layout/item_result.xml
> +    <LinearLayout
수정했습니다. 굳이 LinearLayout을 쓸 필요가 없었겠네요.

2024-07-07 09:07 UTC, omjoonkim approved these changes
2주차 과제 수고하셨습니다. 코드는 머지하도록 할게요~!

2024-07-07 09:07 UTC, merged