전남대 Android_최영빈_2주차 과제_Step2
kakao-tech-campus-2nd-step2/android-map-keyword pull request #53
Opened 2024-07-05 08:19 UTC by yb0x00

2주차 1단계 PR : https://github.com/kakao-tech-campus-2nd-step2/android-map-keyword/pull/30

## 과제를 통해 얻어가고 싶었던 부분
- MVVM 패턴에서 SQLite 사용에 대한 구조 이해
- ListView를 사용 경험 : 라이브 강의를 수강 하면서

>  ListView를 사용해보는 경험이 필요하고,
binding 대신 findViewById 사용을 하는 것이 지금 단계에서 필요함

을 알게되어, 과제 요구 사항에 맞춰 저장된 검색어 목록은 ListView로 구현하고, 검색 결과는 RecyclerView로 구현하고자 하였습니다.

## 코드 작성하면서 어려웠던 점
- MVVM 패턴을 적용해보려고 하였는데 코드가 많이 복잡해진 것 같습니다.
- ListView를 사용해보는 것을 이번 과제에 큰 목표 중 하나로 삼게 되면서 2단계에서도 ListView를 사용하고자 하였습니다. ListView 사용이 더 어렵게 느껴졌습니다. 현재 ListView를 가로 스크롤이 되도록 구현하지 못하였고, X버튼을 눌러 저장된 검색어를 DB에서 삭제하는 기능을 구현하지 못하였습니다.

## 멘토님이 중점적으로 리뷰해주셨으면 하는 부분
- +) step1의 리펙토링을 진행하지 않은 상황이기 때문에 혹시 몰라 2단계 과제를 'pre_step2' branch를 만들어 진행하였고 'pre_step2' branch의 내용을 PR 하는 상황입니다.
RecyclerView를 사용해 step2의 요구사항을 모두 구현하는 것이 우선적인 목표여서 우선은 ListView를 사용하지 않고 진행하는 것이 더 바람직한 진행 방향인지 궁금합니다.

- 현재 ListView의 X버튼을 클릭하여 저장된 검색어를 DB에서 삭제하는 부분을 구현하지 못했습니다. RecyclerView를 사용할 때는 Adapter의 onBindViewHolder()에서 진행하였는데 ListView에서는 어디에서 기능하도록 해야 하는지 답을 찾지 못한 상황입니다. 조언부탁드립니다.

- 구글링을 했을 때, ListView를 가로로 스크롤 가능하게 하기 위해서 HorizontalScrollView를 사용하면 되는 것 같은데 현재 구현하지 못한 상황입니다. 조언부탁드립니다.

- 최근 검색어가 ListView의 앞쪽에 위치하게 하기 위해, 최근 검색어를 저장하는 DB에서 최근 검색어가 위쪽 행으로 이동해야 할 것 같습니다. DB의 순서를 바꾸는 방법에 대해 여쭙고 싶습니다.

- MVVM을 적용하고자 하였는데 현재 코드가 복잡하게 느껴집니다. 어떤 식으로 작성(또는 정리)하면 좋을지 여쭙고 싶습니다.

- 한번에 여러 파일을 commit해도 리뷰하실 때 보기 편하신지 궁금합니다.

## 과제 수행하면서 느낀점
- step1부터 지금까지 학습하면서 얼마나 사고하였나 성찰하였습니다. 코드가 길어지다 보니 어디에 어떤 코드가 필요한지 등 중간에 길을 잃어버린 경우가 많았습니다. 프로그램 실행에 대한 전체 프로세스 관련 추가 학습이 필요한 것 같습니다.

- 과제 제출이 늦어짐에 있어 step2 과정을 제대로 따라가고 있는 것인지 걱정이 되었습니다.

2024-07-05 14:44 UTC, omjoonkim requested changes
> RecyclerView를 사용해 step2의 요구사항을 모두 구현하는 것이 우선적인 목표여서 우선은 ListView를 사용하지 않고 진행하는 것이 더 바람직한 진행 방향인지 궁금합니다.

ListView가 무엇이고 RecyclerView가 왜 나오게 되었는지를 파악하는 것이 중요합니다. 차이에 대해서 이하고 계시다면 RecyclerView를 사용하셔도 무방하다고 생각됩니다.

> 현재 ListView의 X버튼을 클릭하여 저장된 검색어를 DB에서 삭제하는 부분을 구현하지 못했습니다. RecyclerView를 사용할 때는 Adapter의 onBindViewHolder()에서 진행하였는데 ListView에서는 어디에서 기능하도록 해야 하는지 답을 찾지 못한 상황입니다. 조언부탁드립니다.

ListView를 작성할 때는 보통 ViewHolder 패턴을 직접 구현하여 사용하게 됩니다.  [블로그 글](https://jcchu.medium.com/viewholder-pattern%EC%97%90-%EB%8C%80%ED%95%B4-%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0-9838e66ea9a5)을 참고해보세요. 

> 구글링을 했을 때, ListView를 가로로 스크롤 가능하게 하기 위해서 HorizontalScrollView를 사용하면 되는 것 같은데 현재 구현하지 못한 상황입니다. 조언부탁드립니다.

RecyclerView 사용을 권장드립니다. ㅎㅎ

> 최근 검색어가 ListView의 앞쪽에 위치하게 하기 위해, 최근 검색어를 저장하는 DB에서 최근 검색어가 위쪽 행으로 이동해야 할 것 같습니다. DB의 순서를 바꾸는 방법에 대해 여쭙고 싶습니다.

DB의 순서를 바꾸는 것이 아닌 저장된 시간을 테이블에 함께 저장하고, 데이터를 조회한 뒤 해당 시간에 따라 정렬하여 UI에 표현하도록 만들어보세요.

> MVVM을 적용하고자 하였는데 현재 코드가 복잡하게 느껴집니다. 어떤 식으로 작성(또는 정리)하면 좋을지 여쭙고 싶습니다.

어떤 코드가 복잡하다고 느끼시는지 말씀해주시면 답변을 드릴 수 있을 것 같습니다. :) 

> 한번에 여러 파일을 commit해도 리뷰하실 때 보기 편하신지 궁금합니다.

네 파일 개수와는 무관합니다. 코드양이 중요합니다. ㅎㅎ

이전 PR의 코멘트도 함께 반영 부탁드려요~!

2024-07-05 14:44 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/RecentDataRepository.kt
> +        wDb.delete(RecentDataContract.TABLE_NAME,RecentDataContract.TABLE_COLUMN_NAME, arrayOf(data))
nit; 하나의 함수에 여러 파라미터가 필요할 경우, 파라미터별로 라인을 나누는게 코드를 읽기에 더 좋습니다.

2024-07-05 14:44 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/DataSearchActivity.kt
> +    private fun clickDeleteBtn(){
함수명과 구현되어있는 코드가 매치되지 않습니다. 뷰에 리스너를 추가한다는 코드 의미에 맞게 함수명을 수정해보세요.

2024-07-05 14:44 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/DataSearchActivity.kt
> +                }else{noResultNotice.visibility = View.VISIBLE
코드 정리가 되면 좋을 것 같습니다. IDE에서 제공하는 기본 코드 포맷팅 커맨드를 사용해보세요.

2024-07-05 14:44 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/DataSearchActivity.kt
> +                    resultDataAdapter = SearchDataAdapter(emptyList(),recentViewModel)
매번 어뎁터를 생성하지마시고, 어뎁터를 생성한 이후 필요할때마다 내부 데이터를 변경하도록 코드를 변경해주세요.

2024-07-05 14:44 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/DataSearchActivity.kt
> +        textWatcher = object:TextWatcher{
textWatcher를 필드로 선언해서 사용할 이유가 현재로서는 없는 것 같습니다. 곧바로 editText에 추가하는 것이 어떨까요?

2024-07-05 14:44 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/RecentSearchAdapter.kt
> +        if (convertView == null){
```suggestion
   val view =     if (convertView == null){
```
위와같이 코드를 작성하면 불필요한 선언 코드를 제거할 수 있습니다.

2024-07-05 14:44 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/RecentViewModel.kt
> +    fun getRecentDataLiveData(): MutableLiveData<List<String>>{
MutableLiveData를 리턴 할 경우 뷰모델 외부에서 값이 변경되어 사이드 이펙트를 발생시킬 수 있습니다. MutbleLiveData대신 LiveData를 반환하도록 변경해보세요.

2024-07-07 12:21 UTC, yb0x00 commented on app/src/main/java/campus/tech/kakao/map/RecentDataRepository.kt
> +        wDb.delete(RecentDataContract.TABLE_NAME,RecentDataContract.TABLE_COLUMN_NAME, arrayOf(data))
반영했습니다:) 피드백 감사합니다!

+) 이전 PR 반영 후 여기로 넘어왔습니다. 이전 PR에 남긴 comment도 확인 부탁드립니다!

2024-07-07 12:32 UTC, yb0x00 commented on app/src/main/java/campus/tech/kakao/map/DataSearchActivity.kt
> +    private fun clickDeleteBtn(){
resetButtonListener()로 함수명 수정했습니다. 피드백 감사합니다!

2024-07-07 12:42 UTC, yb0x00 commented on app/src/main/java/campus/tech/kakao/map/DataSearchActivity.kt
> +                }else{noResultNotice.visibility = View.VISIBLE
피드백 감사합니다!
Reformat code(Ctrl+Alt+L)를 사용해서 수정했습니다.

2024-07-07 14:00 UTC, omjoonkim approved these changes
요구사항을 보면 
1. 검색어를 저장하고 
2. 검색어를 삭제할 수 있어야 합니다. 

지금 구현하신 코드를 보면 검색어를 저장하는 것이 아닌 검색 결과 아이템을 저장하는 것으로 보여집니다.

코멘트를 참고하여 요구사항을 올바르게 구현해보세요. :) 

PR은 규정에 따라 우선 머지하도록 하겠습니다~!

2024-07-07 14:00 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/SearchDataAdapter.kt
> +            recentViewModel.addRecentData(item.name)
검색 결과가 아닌 검색어를 입력했을 때 데이터를 저장하도록 변경해보세요~!

2024-07-07 14:00 UTC, merged

2024-07-07 14:19 UTC, yb0x00 commented on app/src/main/java/campus/tech/kakao/map/DataSearchActivity.kt
> +                    resultDataAdapter = SearchDataAdapter(emptyList(),recentViewModel)
수정했습니다! 피드백 감사합니다!

2024-07-07 14:39 UTC, yb0x00 commented on app/src/main/java/campus/tech/kakao/map/DataSearchActivity.kt
> +        textWatcher = object:TextWatcher{
수정했습니다! 피드백 감사합니다!

코드를 작성할 때
의식적으로 진짜 필요한 문장인지 다시 한번 생각하도록 연습해야겠습니다..!

2024-07-07 14:50 UTC, yb0x00 commented on app/src/main/java/campus/tech/kakao/map/RecentSearchAdapter.kt
> +        if (convertView == null){
```
override fun getView(position: Int, convertView: View?, parent: ViewGroup?): View {
        val view: View
        val recentDataViewHolder : RecentViewHolder
        if (convertView == null){
            view = LayoutInflater.from(parent?.context).inflate(R.layout.recent_search_item,parent,false)
            recentDataViewHolder = RecentViewHolder(view)
            view.tag = recentDataViewHolder
        } else{
            view = convertView
            recentDataViewHolder = convertView.tag as RecentViewHolder
        }
        val item = recentDataList[position]
        recentDataViewHolder.name.text = item

        return view
    }
```
if문에서 ViewHolder와 tag 설정을 같이 하기 때문에 view에 바로 값을 넣는 형식은 적용이 어려울 것 같습니다. 확인부탁드립니다!

2024-07-07 14:55 UTC, omjoonkim commented on app/src/main/java/campus/tech/kakao/map/RecentSearchAdapter.kt
> +        if (convertView == null){
```suggestion
       val view = convertView ?: LayoutInflater.from(parent?.context).inflate(R.layout.recent_search_item,parent,false)
        val recentDataViewHolder = view.tag as? RecentViewHolder ?: RecentViewHolder(view).also { view.tag = it }
        recentDataViewHolder.name.text = getItem(position) as String
```
이렇게 간단하게 작성해볼 수 있을 것 같아요~!

2024-07-07 15:14 UTC, yb0x00 commented on app/src/main/java/campus/tech/kakao/map/RecentSearchAdapter.kt
> +        if (convertView == null){
우와...! 정말 멋있습니다...!
코틀린의 매력은 엄청난 것 같습니다

코드 수정했습니다! 피드백 감사합니다!!!

2024-07-07 15:22 UTC, yb0x00 commented on app/src/main/java/campus/tech/kakao/map/RecentViewModel.kt
> +    fun getRecentDataLiveData(): MutableLiveData<List<String>>{
수정했습니다! 피드백 감사합니다!

2024-07-07 17:17 UTC, yb0x00 commented on app/src/main/java/campus/tech/kakao/map/SearchDataAdapter.kt
> +            recentViewModel.addRecentData(item.name)
검색어를 삭제하는 기능을 추가하여 commit하였습니다.

현재 리스트뷰를 사용하면서 3단계에 해당하는 기능을 구현하였고,
2단계의 '검색어 목록 가로 스크롤' 기능 구현만 하지 못한 상황인 것 같습니다.
추가적으로 리스트뷰를 리사이클뷰로 바꾸어 가로 스크롤이 가능하게까지 수행해야할지 여쭙고 싶습니다.

+)시간되실때 https://github.com/kakao-tech-campus-2nd-step2/android-map-keyword/pull/30 의 windowSoftInputMode에 대한 질문 확인 부탁드립니다.

감사합니다!