강원대 Android_권새일 2주차 과제 Step2
kakao-tech-campus-2nd-step2/android-map-keyword pull request #54
Opened 2024-07-05 08:30 UTC by todlf

**어려웠던 점**
- 이번주에 다른 일정으로 인해 시간이 없어서 검색어 저장 결과 recyclerView를 적용시키다가 과제를 제출하게 되었습니다😥
-  RecyclerView, SQLite 적용시키는 게 아직은 어렵습니다. 
- 아직 findViewbyId가 익숙하지 않아서 binding을 사용하지 않았습니다.
- 
**중점적으로 리뷰해주셨으면 하는 부분**
- RecyclerView에서 Scroll 할 때 데이터가 뒤죽박죽으로 떠서 찾아보니 `getItemViewType`을 넣으면 된다는데 해결이 안되서 어느 부분이 문제인지 궁금합니다
- 그 외 Layout이나 Activity의 코드를 작성하는데 있어서 불필요하거나 더 좋은 코드가 있다면 알려주시면 좋겠습니다!

2024-07-06 06:12 UTC, kold-brewed requested changes

2024-07-06 06:12 UTC, kold-brewed commented on app/src/main/res/layout/item_search.xml
> +    <FrameLayout
레이아웃 xml을 정의하는 부분에 있어서 조금 어려움을 겪고 계시는 것 같아요.

최우선적으로 여기 FrameLayout은 제거해주시면 좋겠어요!
step1 PR 리뷰에도 코멘트 남겨드린 부분이긴 하지만 한번더 말씀드려봅니다 ㅎㅎ

FrameLayout은 이번 과제의 요구사항에 해당하는 화면을 그리는 용도에는 적합하지 않아요.
이 레이아웃에 포함되는 뷰들은 정의하는 순서대로 위로 겹쳐집니다. 

앞으로 과제를 진행하실 때에도 Layout을 추가하지 않고, 1번 라인에 정의된 부모 레이아웃인 ConstraintLayout만을 이용해서 뷰들의 위치를 정의하셨으면 해요.
```xml
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
```

2024-07-06 06:12 UTC, kold-brewed commented on app/src/main/res/layout/item_search.xml
> +        <androidx.constraintlayout.widget.ConstraintLayout
여기 있는 ConstraintLayout도 불필요하게 정의된 부분이라 FrameLayout과 같이 제거해주셨으면 합니다.
역시 1번라인의 부모 ConstriantLayout만으로 나머지 뷰들의 위치를 정해줄 수 있어요!

2024-07-06 06:12 UTC, kold-brewed commented on app/src/main/res/layout/item_search.xml
> +                android:background="@android:color/transparent" />
이 버튼은 어떤 용도로 사용하고 싶으신 건지 궁금합니다~

2024-07-06 06:12 UTC, kold-brewed commented on app/src/main/res/layout/item_search.xml
> +                app:layout_constraintStart_toEndOf="@id/locationImage" />
ConstraintLayout 내에 정의되는 뷰들은 수평, 수직 각각 1개씩은 위치에 대한 속성을 정의해주셔야해요. 
앱이 실행될 때 가로 세로로 뷰를 얼만큼의 크기로 계산해 그려줄지에 관한 부분이라서요!
리뷰 요청하실 때 적어주셨던 '스크롤 시에 데이터 높이가 뒤죽박죽으로 뜨는 문제'도 이와 관련이 있습니다.

아래 TextView에 start_toEndOf(수평), top_toBottomOf(수직) 정의하신 것 처럼 여기 ImageView와 TextView에도 수직으로 어떻게 위치시킬지도 정의해주세요~

2024-07-06 06:12 UTC, kold-brewed commented on app/src/main/res/layout/item_search.xml
> +                android:text="카테고리"
위에 주소와 카테고리 문자열은 strings.xml에 정의하도록 수정해주세요~

2024-07-06 06:12 UTC, kold-brewed commented on app/src/main/res/layout/item_saveword.xml
> +<?xml version="1.0" encoding="utf-8"?>
xml 이름을 정의하실 때는 스네이크 케이스에 맞춰서 item_save_word.xml과 같이 작성해주시면 좋겠네요!

2024-07-06 06:12 UTC, kold-brewed commented on app/src/main/res/layout/item_saveword.xml
> +        android:textSize="20sp" />
이 TextView를 감싸고 있는 레이아웃은 ConstraintLayout입니다.
수평, 수직으로 어떻게 위치시킬지 속성을 정의해주셔야 해요!

2024-07-06 06:12 UTC, kold-brewed commented on app/src/main/res/layout/item_saveword.xml
> +        app:layout_constraintStart_toEndOf="@id/savedWord" />
여기도 수직 위치 속성이 누락되었습니다~

2024-07-06 06:12 UTC, kold-brewed commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="wrap_content"
목록을 구성하는 RecyclerViewd의 높이를 wrap_content로 설정해두시면 목록 내 아이템이 잘려보일 수도 있을 거예요.
app:layout_constrainedHeight 속성에 대해 알아보신 후 함께 사용하거나 layout_height를 0dp로 변경하시는 쪽을 권해드리고 싶습니다.

2024-07-06 06:25 UTC, kold-brewed requested changes

2024-07-06 06:25 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +
과제 요구사항 중에는 MVVM 패턴에 맞게 작성해보는 내용도 있었습니다. 이번주는 시간이 부족하셨다고해서 혹시나 패턴에 대한 이해가 어렵다면 일단은 미완성된 기능들을 마저 구현하는 것에 집중해주셨으면 해요.

그 후에 Activity에서 데이터베이스에 접근하는 코드들과 Category 기준으로 목록을 필터링 하는 코드는 각각 역할에 맞게 Model 역할의 클래스와 ViewModel 역할의 클래스로 나누어 담아 보시면 좋을 것 같아요. 최종적으로 Activity에는 뷰에 데이터를 세팅하는 코드만 남도록이요!

2024-07-07 02:05 UTC, todlf commented
아이템을 클릭하거나 삭제할 때 검색어 목록의 recyclerview가 바뀌고 검색어 저장 recylcerview의 간격이 있는데 왜 그런지 모르겠습니다😢

2024-07-07 14:14 UTC, kold-brewed commented on app/src/main/res/layout/item_search.xml
> +    android:layout_height="match_parent">
아..! 여기 layout_height 높이 속성 한번 손 봐주셔야 할 것 같아요.
RecyclerView의 아이템뷰는 지금 레이아웃 내에 들어가는 이미지나 이름, 주소로 구성되는 자식뷰들의 높이에 맞게 설정해주시는 것이 좋습니다~

2024-07-07 14:19 UTC, kold-brewed commented on app/src/main/res/layout/item_save_word.xml
> +    android:layout_width="match_parent"
여기도 너비를 부모너비에 맞추도록 되어있어서 "카페 X"뷰에 여백이 그만큼씩 들어갈 수 있을거예요. 이부분도 item_search.xml 부분 코멘트와 같이 수정해주시면 될 것 같아요.

2024-07-07 14:22 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +                true
@todlf 
이렇게하면 검색어 기록이 오른쪽에 갖다붙어서 왼쪽으로 아이템이 늘어날텐데 의도하신 부분이 맞을까요??

2024-07-07 14:31 UTC, todlf commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +                true
의도한 건 아니고 horizontal로 스크롤 되지 않아서 넣은 부분입니다;;

2024-07-07 14:33 UTC, todlf commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +                true
LinearLayoutManager(
                this,
                LinearLayoutManager.HORIZONTAL,
                false
로 고쳐서 해결했습니다!

2024-07-07 15:07 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +    }
고생하셨어요! 코멘트 남겨드린 부분들도 잘 수정해주셨고, 기능들도 잘 동작하는 것 같네요 👏 

시간이 되신다면 MVVM 패턴에 맞게 클래스를 나누는 작업도 해보시면 좋을 것 같은데, 우선 Model 레이어 확실히 분리하는 작업을 먼저 시도해보시면 좋을 것 같아요.

Model은 화면에 그리기 위한 데이터를 담고있는 곳이예요. 네트워크를 통해 서버에게 요청하거나 로컬 데이터베이스에게 데이터를 요청하는 로직을 담게됩니다. 지금은 SearchDbHelper가 그 역할을 하고 있다고 볼 수 있겠네요. View 역할을 하는 MainActivity에 있는saveDb와 loadDb 함수를 SearchDbHelper클래스가 가지도록 수정해보세요. View가 데이터를 어디서 어떻게 가져오는지 모르도록 하기 위한 작업이예요. 그러면 추후에 데이터를 가져오는 곳이 서버로 변경되어도 MainActivity는 건드리지 않아도 되게 됩니다.

2024-07-07 15:13 UTC, merged