부산대 Android_이지은 2주차 2단계 제출
kakao-tech-campus-2nd-step2/android-map-keyword pull request #60
Opened 2024-07-05 08:52 UTC by JieunYume

2024-07-07 14:29 UTC, bigstark requested changes
이번 과제도 고생 많으셨습니다. 

----

> ViewModel 과 관련해서 부족했던 부분을 집어주시면 감사하겠습니다!

ViewModel 의 사용이 어색해보입니다. 비즈니스 로직이라고 불리는 것들이 아직 와닿지는 않겠지만, 최대한 ViewModel 로 이동시키는 것을 권장드려요. 또한 시간 되실 때 안드로이드에서는 [데이터 레이어](https://developer.android.com/topic/architecture/data-layer)를 어떻게 관리하는지 보시면 큰 도움이 될 것입니다. 

> 데이터 삽입, 삭제, 조회 관련 코드를 LocationDbHelper에 넣을지 새로 클래스(LocationDbAccessor)를 만들지 고민하다가, 따로 만들기로 결정했습니다. 옳은 판단이었을까요??

매우 옳은 판단이고 칭찬드리고 싶습니다. DAO 의 개념을 차용하신 부분이라고 생각이 듭니다. 더 나아가 [Room](https://developer.android.com/training/data-storage/room) 을 통해 관리한다면 조금 더 수월하게 코드작성이 되지 않을까 싶습니다.

2024-07-07 14:29 UTC, bigstark commented on app/src/main/java/campus/tech/kakao/map/LocationAdapter.kt
> +    }) {
오 ListAdapter 너무 좋습니다 💯

2024-07-07 14:29 UTC, bigstark commented on app/src/main/java/campus/tech/kakao/map/LocationAdapter.kt
> +    }
LocationViewHodler 가 LocationAdapter 의 것을 참조하지 않는 것이 좋습니다. (getItem 과 onLocationSelected) 
이를 inner class 가 아니고 parameter 로 받든가, 해서 처리하시는 것을 추천드려요.
```suggestion
    class LocationHolder(
        itemView: View, 
        private val onLocationSelected: (Int) -> Unit
    ) : RecyclerView.ViewHolder(itemView) {
        val titleTextView: TextView = itemView.findViewById(R.id.titleTextView)
        val addressTextView: TextView = itemView.findViewById(R.id.addressTextView)
        val categoryTextView: TextView = itemView.findViewById(R.id.categoryTextView)

        init {
            itemView.setOnClickListener {
                onLocationSelected(bindingAdapterPosition)
            }
        }
    }
```

2024-07-07 14:29 UTC, bigstark commented on app/src/main/java/campus/tech/kakao/map/LocationViewModel.kt
> +    val locations: LiveData<List<Location>> get() = _locations
locations 를 사용하고 있지 않습니다. 사용할 의도가 있다면 수정해주시면 되고, 없다면 제거부탁드려요!

2024-07-07 14:29 UTC, bigstark commented on app/src/main/java/campus/tech/kakao/map/LocationViewModel.kt
> +        }
음.. 아쉽습니다. 만약 location 이 10만개가 넘어가는 상황에서 한번에 데이터를 불러오지 못하는 경우를 가정했을 때 현재 불러온 것을 filter 하는 것은 검색 데이터를 제대로 넘겨주지 못하는 상황을 발생시킵니다. 검색 쿼리를 통해서 처리하는 것이 어떨까요?

2024-07-07 14:29 UTC, bigstark commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +    private lateinit var NoResultTextView: TextView
요친구만 대문자로 시작하는군요!

2024-07-07 14:29 UTC, bigstark commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +    }
이러한 비즈니스 로직은 최대한 ViewModel 로 이동하길 권장드립니다 :)

2024-07-07 14:29 UTC, bigstark commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +                }
이러한 로직들도 locationViewModel.searchLocations(query) 만 호출하도록 하는 것이 좋을 것 같아요. LocationViewModel 내부의 searchLocations 메소드가 query 검사를 하는 것이 조금 더 좋아보입니다.

2024-07-07 14:29 UTC, bigstark commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
>      }
요런 init 코드들도 마찬가지입니다! ViewModel 로 이동하길 권장합니다. :)

2024-07-10 18:04 UTC, bigstark commented on app/src/main/java/campus/tech/kakao/map/MainActivity.kt
> +        locationViewModel.insertLocation() // 앱 설치 시 최초 1번만 실행하게 하려면 어떻게 해야할까?
앱설치 시 한번만 실행되게 하려면 [Application](https://guides.codepath.com/android/Understanding-the-Android-Application-Class) 의 onCreate 에서 처리하면 될 것 같습니다 :)

2024-07-10 18:06 UTC, bigstark commented on app/src/main/java/campus/tech/kakao/map/onItemSelected.kt
> +interface onItemSelected {
사소한 것이지만, interface 또한 대문자로 시작하면 좋을 것 같고, listener 라면 postfix 로 ####Listener 로 붙여주시면 조금 더 보기 좋습니다!
```suggestion
interface OnItemSelectedListener
```

2024-07-10 18:09 UTC, bigstark approved these changes
지은님 3주차 과제를 진행 중이실텐데, 정말 수고 많으셨어요! 

안드로이드에서 ViewModel 을 조금 더 잘 쓰려면 [UiState](https://developer.android.com/topic/architecture/ui-layer/stateholders) 에 대해서 조금 더 공부해보시면 좋을 것 같아요!

또한 ViewModel 내부에서 데이터를 다루기 위한 방법으로 [data layer](https://developer.android.com/topic/architecture/data-layer)  에 대한 공부를 해보시면 큰 도움이 되지 않을까 싶습니다 :)

2024-07-10 18:12 UTC, JieunYume commented on app/src/main/java/campus/tech/kakao/map/onItemSelected.kt
> +interface onItemSelected {
우와 빠른 리뷰 감사합니다~!

2024-07-10 18:15 UTC, merged