부산대 Android_김정희_2주차 과제_1단계
kakao-tech-campus-2nd-step2/android-map-keyword pull request #8
Opened 2024-07-02 07:16 UTC by lovelhee

안녕하세요 멘토님 :) 
항상 감사드립니다. 오늘도 코드 리뷰 부탁드립니다!

### 중점으로 봐주셨으면 하는 부분
MVVM 패턴 적용을 처음 해봐서 부족한 부분이 있으리라 예상됩니다.
해당 부분을 올바르게 구현했는지 중점으로 봐주시면 감사하겠습니다!

---

### 마무리 및 질문

1. 과제를 보았을 때 현재 구현하는 레이아웃의 주된 기능은 검색창이라고 생각합니다. 
   그래서 SearchView를 사용할까 싶다가도 과제의 예시 화면을 보았을 땐 EditText를 사용하는 거 같았습니다.
   이런 경우에서는 SearchView와 EditText 중 어떤 것으로 구현하는 것이 더 효과적일까요?

2. 삽입될 데이터는 카페로 예시를 들면 카페1, 카페2, ... 카페10으로 넣었습니다.
   이때, 한 번 실행할 때마다 1..10이 다 삽입되어 최종적으로 카페1..10이 3번 들어가있는 것을 확인하였습니다.
   제가 생각했을 때는 필요한 건 카페1..10까지 한 번만 삽입되는 건데, 이런 경우를 방지하기 위해선 어떻게 해야할까요?
    
![image](https://github.com/kakao-tech-campus-2nd-step2/android-map-keyword/assets/165051638/4e36bde1-4257-4d25-bfdc-724922090161)

---

오늘도 좋은 하루 되시길 바랍니다. 감사합니다!

2024-07-04 18:14 UTC, LeeOhHyung requested changes
@lovelhee 2주차 step1 과제도 고생많으셨습니다.
데이터가 중복으로 삽입되는것은 수정이 필요할것 같습니다. 수정후에 말씀주시면 다시 확인해보도록 할게요

2024-07-04 18:14 UTC, LeeOhHyung commented on app/src/main/java/campus/tech/kakao/map/MapViewModel.kt
> +}
>삽입될 데이터는 카페로 예시를 들면 카페1, 카페2, ... 카페10으로 넣었습니다.
이때, 한 번 실행할 때마다 1..10이 다 삽입되어 최종적으로 카페1..10이 3번 들어가있는 것을 확인하였습니다.
제가 생각했을 때는 필요한 건 카페1..10까지 한 번만 삽입되는 건데, 이런 경우를 방지하기 위해선 어떻게 해야할까요?

이 부분이 원인으로 보입니다. 앱이 실행될때마다 MapViewModel이 새로 만들어지고, MainActivity의 onCreate에서 매번 호출하고 있으므로, 데이터가 여러번 들어가는 현상이 발생합니다. 따라서, 이미 데이터가 존재하는지 체크해서 없는경우만 insertData가 호출되게 처리하거나 or DbHelper의 onCreate(...) 에서 하는 등 1회만 호출되도록 처리해줘야 할것 같습니다

2024-07-04 18:14 UTC, LeeOhHyung commented on app/src/main/res/layout/activity_main.xml
> +            android:paddingEnd="50dp" />
>과제를 보았을 때 현재 구현하는 레이아웃의 주된 기능은 검색창이라고 생각합니다.
그래서 SearchView를 사용할까 싶다가도 과제의 예시 화면을 보았을 땐 EditText를 사용하는 거 같았습니다.
이런 경우에서는 SearchView와 EditText 중 어떤 것으로 구현하는 것이 더 효과적일까요?

SearchView는 검색어를 입력했을때 / 검색을 수행할때 호출되는 Listener를 제공해주기 때문에 바로 사용하시면 됩니다. 반면에 EditText를 사용한다면 TextWatcher를 사용해서 검색기능을 사용할 수 있도록 직접 구현이 필요하다는 차이가 있습니다. 

`SearchView` 는 검색기능 제작을 손쉽게 도와주기 위한 위젯이기 때문에 처음에는 이걸 활용하는게 난이도는 쉽게 느껴지실겁니다. 하지만, EditText를 사용해서 검색창을 만들때도 많이 있으므로 둘다 사용해보고 장단점을 비교하는것이 당연히 더 좋겠죠.

2024-07-05 05:01 UTC, lovelhee commented on app/src/main/res/layout/activity_main.xml
> +            android:paddingEnd="50dp" />
감사합니다! 2주차 과제는 예시 화면과 똑같이 만들어보고싶어서 EditText로 진행하려고 합니다. 그래도 알려주신 거처럼 SearchView에 대해서도 함께 공부해보겠습니다!

2024-07-05 05:53 UTC, lovelhee commented on app/src/main/java/campus/tech/kakao/map/MapViewModel.kt
> +}
감사합니다! 데이터가 존재하는지 체크해서 데이터가 없을 때 insertData가 호출되도록 처리하려고 합니다. 해당 변경사항을 step2 제출 때 함께 제출하겠습니다!

2024-07-08 05:01 UTC, LeeOhHyung approved these changes
LGTM~

2024-07-08 05:01 UTC, merged